import { Injectable } from '@angular/core';
import { AnalysisResult } from './ai-analysis.service';
import { DatasetMetadata } from './dataset-parser.service';

export interface ReportConfig {
  title: string;
  format: 'pdf' | 'csv' | 'excel';
  includeCharts: boolean;
  includeRawData: boolean;
  selectedResults: string[];
}

@Injectable({
  providedIn: 'root'
})
export class ReportGeneratorService {
  
  constructor() {}

  async generateReport(
    results: AnalysisResult[], 
    metadata: DatasetMetadata,
    config: ReportConfig
  ): Promise<Blob> {
    const selectedResults = results.filter(r => config.selectedResults.includes(r.id));
    
    switch (config.format) {
      case 'pdf':
        return this.generatePDF(selectedResults, metadata, config);
      case 'csv':
        return this.generateCSV(selectedResults);
      case 'excel':
        return this.generateExcel(selectedResults, metadata);
      default:
        throw new Error('Unsupported format');
    }
  }

  private generatePDF(results: AnalysisResult[], metadata: DatasetMetadata, config: ReportConfig): Blob {
    // Create a simple text-based report (in production, use a PDF library)
    let content = this.createPDFContent(results, metadata, config);
    
    return new Blob([content], { type: 'text/plain' });
  }

  private createPDFContent(results: AnalysisResult[], metadata: DatasetMetadata, config: ReportConfig): string {
    let content = '';
    
    // Header
    content += '='.repeat(60) + '\n';
    content += `AI ANALYSIS REPORT\n`;
    content += '='.repeat(60) + '\n\n';
    
    // Dataset Info
    content += 'DATASET INFORMATION\n';
    content += '-'.repeat(40) + '\n';
    content += `File: ${metadata.filename}\n`;
    content += `Rows: ${metadata.rowCount}\n`;
    content += `Columns: ${metadata.columnNames.join(', ')}\n`;
    content += `Generated: ${new Date().toLocaleString()}\n\n`;
    
    // Results
    content += 'ANALYSIS RESULTS\n';
    content += '-'.repeat(40) + '\n\n';
    
    results.forEach((result, index) => {
      content += `${index + 1}. ${result.title}\n`;
      content += `   Type: ${result.type}\n`;
      content += `   ${result.content}\n\n`;
    });
    
    // Footer
    content += '='.repeat(60) + '\n';
    content += 'Generated by DataVision AI Assistant\n';
    
    return content;
  }

  private generateCSV(results: AnalysisResult[]): Blob {
    let csv = 'Type,Title,Content,Timestamp\n';
    
    results.forEach(result => {
      const row = [
        result.type,
        `"${result.title.replace(/"/g, '""')}"`,
        `"${result.content.replace(/"/g, '""').replace(/\n/g, ' ')}"`,
        result.timestamp.toISOString()
      ];
      csv += row.join(',') + '\n';
    });
    
    return new Blob([csv], { type: 'text/csv' });
  }

  private generateExcel(results: AnalysisResult[], metadata: DatasetMetadata): Blob {
    // Simplified Excel format (CSV with metadata sheet)
    let content = 'METADATA\n';
    content += `Filename,${metadata.filename}\n`;
    content += `Rows,${metadata.rowCount}\n`;
    content += `Columns,"${metadata.columnNames.join(', ')}"\n`;
    content += `Generated,${new Date().toISOString()}\n\n`;
    
    content += 'RESULTS\n';
    content += 'Type,Title,Content,Timestamp\n';
    
    results.forEach(result => {
      const row = [
        result.type,
        `"${result.title.replace(/"/g, '""')}"`,
        `"${result.content.replace(/"/g, '""').replace(/\n/g, ' ')}"`,
        result.timestamp.toISOString()
      ];
      content += row.join(',') + '\n';
    });
    
    return new Blob([content], { type: 'text/csv' });
  }

  downloadReport(blob: Blob, filename: string) {
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = filename;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  }

  generateReportName(format: string): string {
    const timestamp = new Date().toISOString().slice(0, 10);
    return `ai-report-${timestamp}.${format === 'excel' ? 'csv' : format}`;
  }
}